name: Builll

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        java-version: [17,21,24]

        include:
          - os: ubuntu-latest
            java-version: 8

        exclude:
         - os: windows-latest
           java-version: 11

         - os: macos-latest
           java-version: 24

      fail-fast: true

      max-parallel: 5
    steps:
      - name: pp
        uses: actions/checkout@v4
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
            
          
    
